// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogDocumentDataSlicesSlice = StorySectionSlice;

/**
 * Content for Blog documents
 */
interface BlogDocumentData {
  /**
   * Featured Blog  Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.blog_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  blog_image: prismic.ImageField<never>;

  /**
   * Blog Title field in *Blog*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.blog_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  blog_title: prismic.RichTextField;

  /**
   * Blog Title Short (optional) field in *Blog*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.blog_title_short
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  blog_title_short: prismic.RichTextField;

  /**
   * Blog Description field in *Blog*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.blog_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  blog_description: prismic.RichTextField;

  /**
   * Blog Tip Type field in *Blog*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Bathroom Tips
   * - **API ID Path**: blog.blog_tip_type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  blog_tip_type: prismic.SelectField<
    | "Bathroom Tips"
    | "Interior tips"
    | "Kitchen Tips"
    | "Living Tips"
    | "Remodeling Tips",
    "filled"
  >;

  /**
   * Blog Date field in *Blog*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.blog_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  blog_date: prismic.DateField;

  /**
   * Owner field in *Blog*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.owner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  owner: prismic.ContentRelationshipField<"owner">;

  /**
   * Article Read Time field in *Blog*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.read_time
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  read_time: prismic.NumberField;

  /**
   * Slice Zone field in *Blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, "blog", Lang>;

type FeaturedProjectDocumentDataSlicesSlice = StorySectionSlice;

/**
 * Content for Featured Project documents
 */
interface FeaturedProjectDocumentData {
  /**
   * Featured Project Image field in *Featured Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_project.project_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  project_image: prismic.ImageField<never>;

  /**
   * Show Featured Image On Project Page field in *Featured Project*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: featured_project.display_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  display_image: prismic.BooleanField;

  /**
   * Project Title field in *Featured Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_project.project_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  project_title: prismic.KeyTextField;

  /**
   * Project Category Tag field in *Featured Project*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Kitchen Design
   * - **API ID Path**: featured_project.project_tag
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  project_tag: prismic.SelectField<
    | "Kitchen Design"
    | "Remodeling Design"
    | "New Home Design"
    | "Interior Design",
    "filled"
  >;

  /**
   * Project Location field in *Featured Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_project.project_location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  project_location: prismic.KeyTextField;

  /**
   * Project Date field in *Featured Project*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_project.project_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  project_date: prismic.DateField;

  /**
   * Owner field in *Featured Project*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_project.owner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  owner: prismic.ContentRelationshipField<"owner">;

  /**
   * Slice Zone field in *Featured Project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_project.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FeaturedProjectDocumentDataSlicesSlice> /**
   * Meta Title field in *Featured Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: featured_project.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Featured Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: featured_project.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Featured Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_project.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Featured Project document from Prismic
 *
 * - **API ID**: `featured_project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FeaturedProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FeaturedProjectDocumentData>,
    "featured_project",
    Lang
  >;

/**
 * Item in *Navigation → Links*
 */
export interface NavigationDocumentDataLinksItem {
  /**
   * Label field in *Navigation → Links*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Optional - Label for the link
   * - **API ID Path**: navigation.links[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.TitleField;

  /**
   * Link field in *Navigation → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for navigation item
   * - **API ID Path**: navigation.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Custom CSS Class field in *Navigation → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[].custom_css_class
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  custom_css_class: prismic.KeyTextField;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

/**
 * Content for Owner documents
 */
interface OwnerDocumentData {
  /**
   * Owner Image field in *Owner*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: owner.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Owner Name field in *Owner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: owner.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Owner Title field in *Owner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: owner.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Owner document from Prismic
 *
 * - **API ID**: `owner`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OwnerDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<OwnerDocumentData>, "owner", Lang>;

type PageDocumentDataSlicesSlice =
  | FeaturedProjectsSlice
  | ProjectHeaderSlice
  | HeroSlice
  | SectionHeaderSlice
  | InspiredDesignSlice
  | QuoteSlice
  | TextSlice
  | ImageSlice
  | ImageCardsSlice
  | TextWithImageSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Parent field in *Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.parent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  parent: prismic.ContentRelationshipField<"page">;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title of the site
   * - **API ID Path**: settings.siteTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  siteTitle: prismic.TitleField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | BlogDocument
  | FeaturedProjectDocument
  | NavigationDocument
  | OwnerDocument
  | PageDocument
  | SettingsDocument;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Button Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;

  /**
   * Background Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.backgroundImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  backgroundImage: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Image → Default → Primary*
 */
export interface ImageSliceDefaultPrimary {
  /**
   * Image field in *Image → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Image → Banner → Primary*
 */
export interface ImageSliceBannerPrimary {
  /**
   * Image field in *Image → Banner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.banner.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Banner variation for Image Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceBanner = prismic.SharedSliceVariation<
  "banner",
  Simplify<ImageSliceBannerPrimary>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault | ImageSliceBanner;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Item in *ImageCards → Default → Primary → Cards*
 */
export interface ImageCardsSliceDefaultPrimaryCardsItem {
  /**
   * Image field in *ImageCards → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.cards[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Text field in *ImageCards → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.cards[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Button Link field in *ImageCards → Default → Primary → Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.cards[].buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button Text field in *ImageCards → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.cards[].buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;
}

/**
 * Primary content in *ImageCards → Default → Primary*
 */
export interface ImageCardsSliceDefaultPrimary {
  /**
   * Heading field in *ImageCards → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Cards field in *ImageCards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cards: prismic.GroupField<Simplify<ImageCardsSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for ImageCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: ImageCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageCardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageCards*
 */
type ImageCardsSliceVariation = ImageCardsSliceDefault;

/**
 * ImageCards Shared Slice
 *
 * - **API ID**: `image_cards`
 * - **Description**: ImageCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageCardsSlice = prismic.SharedSlice<
  "image_cards",
  ImageCardsSliceVariation
>;

/**
 * Item in *InspiredDesign → Default → Primary → Services*
 */
export interface InspiredDesignSliceDefaultPrimaryServicesItem {
  /**
   * Service Image field in *InspiredDesign → Default → Primary → Services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: inspired_design.default.primary.services[].service_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  service_image: prismic.ImageField<never>;

  /**
   * Service Header field in *InspiredDesign → Default → Primary → Services*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Interior Design
   * - **API ID Path**: inspired_design.default.primary.services[].service_header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  service_header: prismic.TitleField;

  /**
   * Service Text field in *InspiredDesign → Default → Primary → Services*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Interiors with surprising colors, textures, and details.
   * - **API ID Path**: inspired_design.default.primary.services[].service_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  service_text: prismic.RichTextField;

  /**
   * Service Link field in *InspiredDesign → Default → Primary → Services*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Discover More
   * - **API ID Path**: inspired_design.default.primary.services[].service_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  service_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *InspiredDesign → Default → Primary*
 */
export interface InspiredDesignSliceDefaultPrimary {
  /**
   * Services field in *InspiredDesign → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: inspired_design.default.primary.services[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  services: prismic.GroupField<
    Simplify<InspiredDesignSliceDefaultPrimaryServicesItem>
  >;
}

/**
 * Default variation for InspiredDesign Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InspiredDesignSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InspiredDesignSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *InspiredDesign*
 */
type InspiredDesignSliceVariation = InspiredDesignSliceDefault;

/**
 * InspiredDesign Shared Slice
 *
 * - **API ID**: `inspired_design`
 * - **Description**: InspiredDesign
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InspiredDesignSlice = prismic.SharedSlice<
  "inspired_design",
  InspiredDesignSliceVariation
>;

/**
 * Primary content in *Quote → Default → Primary*
 */
export interface QuoteSliceDefaultPrimary {
  /**
   * Quote field in *Quote → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote.default.primary.quote
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.RichTextField;

  /**
   * Source field in *Quote → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote.default.primary.source
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  source: prismic.KeyTextField;
}

/**
 * Default variation for Quote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Quote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuoteSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Quote*
 */
type QuoteSliceVariation = QuoteSliceDefault;

/**
 * Quote Shared Slice
 *
 * - **API ID**: `quote`
 * - **Description**: Quote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSlice = prismic.SharedSlice<"quote", QuoteSliceVariation>;

/**
 * Primary content in *SectionHeader → Default → Primary*
 */
export interface SectionHeaderSliceDefaultPrimary {
  /**
   * eyebrow field in *SectionHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_header.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * title field in *SectionHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_header.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * cursiveText field in *SectionHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_header.default.primary.cursivetext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cursivetext: prismic.KeyTextField;
}

/**
 * Default variation for SectionHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *SectionHeader → no eyebrow → Primary*
 */
export interface SectionHeaderSliceSectionHeaderNoEyebrowPrimary {
  /**
   * title field in *SectionHeader → no eyebrow → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_header.sectionHeaderNoEyebrow.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * cursiveText field in *SectionHeader → no eyebrow → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_header.sectionHeaderNoEyebrow.primary.cursivetext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cursivetext: prismic.KeyTextField;
}

/**
 * no eyebrow variation for SectionHeader Slice
 *
 * - **API ID**: `sectionHeaderNoEyebrow`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionHeaderSliceSectionHeaderNoEyebrow =
  prismic.SharedSliceVariation<
    "sectionHeaderNoEyebrow",
    Simplify<SectionHeaderSliceSectionHeaderNoEyebrowPrimary>,
    never
  >;

/**
 * Slice variation for *SectionHeader*
 */
type SectionHeaderSliceVariation =
  | SectionHeaderSliceDefault
  | SectionHeaderSliceSectionHeaderNoEyebrow;

/**
 * SectionHeader Shared Slice
 *
 * - **API ID**: `section_header`
 * - **Description**: SectionHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionHeaderSlice = prismic.SharedSlice<
  "section_header",
  SectionHeaderSliceVariation
>;

/**
 * Primary content in *Text → Default → Primary*
 */
export interface TextSliceDefaultPrimary {
  /**
   * Text field in *Text → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Text → Two Columns → Primary*
 */
export interface TextSliceTwoColumnsPrimary {
  /**
   * Text field in *Text → Two Columns → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.twoColumns.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Two Columns variation for Text Slice
 *
 * - **API ID**: `twoColumns`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceTwoColumns = prismic.SharedSliceVariation<
  "twoColumns",
  Simplify<TextSliceTwoColumnsPrimary>,
  never
>;

/**
 * Slice variation for *Text*
 */
type TextSliceVariation = TextSliceDefault | TextSliceTwoColumns;

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSlice = prismic.SharedSlice<"text", TextSliceVariation>;

/**
 * Primary content in *TextWithImage → Default → Primary*
 */
export interface TextWithImageSliceDefaultPrimary {
  /**
   * Text field in *TextWithImage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Image field in *TextWithImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for TextWithImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextWithImageSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TextWithImage → With Button → Primary*
 */
export interface TextWithImageSliceWithButtonPrimary {
  /**
   * Text field in *TextWithImage → With Button → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.withButton.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Button Link field in *TextWithImage → With Button → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.withButton.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button Text field in *TextWithImage → With Button → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.withButton.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;

  /**
   * Image field in *TextWithImage → With Button → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.withButton.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * With Button variation for TextWithImage Slice
 *
 * - **API ID**: `withButton`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSliceWithButton = prismic.SharedSliceVariation<
  "withButton",
  Simplify<TextWithImageSliceWithButtonPrimary>,
  never
>;

/**
 * Slice variation for *TextWithImage*
 */
type TextWithImageSliceVariation =
  | TextWithImageSliceDefault
  | TextWithImageSliceWithButton;

/**
 * TextWithImage Shared Slice
 *
 * - **API ID**: `text_with_image`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSlice = prismic.SharedSlice<
  "text_with_image",
  TextWithImageSliceVariation
>;

/**
 * Primary content in *FeaturedProjectsRow → Ratio 1/1.5 → Primary*
 */
export interface FeaturedProjectsSliceRatio115Primary {
  /**
   * Project Left field in *FeaturedProjectsRow → Ratio 1/1.5 → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_projects.ratio115.primary.project_one
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project_one: prismic.ContentRelationshipField<"featured_project">;

  /**
   * Project Right field in *FeaturedProjectsRow → Ratio 1/1.5 → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_projects.ratio115.primary.project_two
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project_two: prismic.ContentRelationshipField<"featured_project">;
}

/**
 * Ratio 1/1.5 variation for FeaturedProjectsRow Slice
 *
 * - **API ID**: `ratio115`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedProjectsSliceRatio115 = prismic.SharedSliceVariation<
  "ratio115",
  Simplify<FeaturedProjectsSliceRatio115Primary>,
  never
>;

/**
 * Primary content in *FeaturedProjectsRow → Ratio 1.5/1 → Primary*
 */
export interface FeaturedProjectsSliceRatio151Primary {
  /**
   * Project Left field in *FeaturedProjectsRow → Ratio 1.5/1 → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_projects.ratio151.primary.project_three
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project_three: prismic.ContentRelationshipField<"featured_project">;

  /**
   * Project Right field in *FeaturedProjectsRow → Ratio 1.5/1 → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_projects.ratio151.primary.project_four
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project_four: prismic.ContentRelationshipField<"featured_project">;
}

/**
 * Ratio 1.5/1 variation for FeaturedProjectsRow Slice
 *
 * - **API ID**: `ratio151`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedProjectsSliceRatio151 = prismic.SharedSliceVariation<
  "ratio151",
  Simplify<FeaturedProjectsSliceRatio151Primary>,
  never
>;

/**
 * Slice variation for *FeaturedProjectsRow*
 */
type FeaturedProjectsSliceVariation =
  | FeaturedProjectsSliceRatio115
  | FeaturedProjectsSliceRatio151;

/**
 * FeaturedProjectsRow Shared Slice
 *
 * - **API ID**: `featured_projects`
 * - **Description**: FeaturedProjects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedProjectsSlice = prismic.SharedSlice<
  "featured_projects",
  FeaturedProjectsSliceVariation
>;

/**
 * Primary content in *ProjectHeader → Default → Primary*
 */
export interface ProjectHeaderSliceDefaultPrimary {
  /**
   * Project Category field in *ProjectHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_header.default.primary.project_category
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  project_category: prismic.KeyTextField;

  /**
   * Project Title field in *ProjectHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_header.default.primary.project_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  project_title: prismic.KeyTextField;

  /**
   * Project Date field in *ProjectHeader → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: project_header.default.primary.project_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  project_date: prismic.DateField;

  /**
   * Project Location field in *ProjectHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_header.default.primary.project_location
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  project_location: prismic.KeyTextField;
}

/**
 * Default variation for ProjectHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectHeader*
 */
type ProjectHeaderSliceVariation = ProjectHeaderSliceDefault;

/**
 * ProjectHeader Shared Slice
 *
 * - **API ID**: `project_header`
 * - **Description**: ProjectHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectHeaderSlice = prismic.SharedSlice<
  "project_header",
  ProjectHeaderSliceVariation
>;

/**
 * Primary content in *ProjectOwner → Default → Primary*
 */
export interface ProjectOwnerSliceDefaultPrimary {
  /**
   * owner field in *ProjectOwner → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project_owner.default.primary.owner
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  owner: prismic.ContentRelationshipField<"owner">;
}

/**
 * Default variation for ProjectOwner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectOwnerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectOwnerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectOwner*
 */
type ProjectOwnerSliceVariation = ProjectOwnerSliceDefault;

/**
 * ProjectOwner Shared Slice
 *
 * - **API ID**: `project_owner`
 * - **Description**: ProjectOwner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectOwnerSlice = prismic.SharedSlice<
  "project_owner",
  ProjectOwnerSliceVariation
>;

/**
 * Primary content in *ProjectSection → Narrative Block width 100% → Primary*
 */
export interface ProjectSectionSliceDefaultPrimary {
  /**
   * Image (optional) field in *ProjectSection → Narrative Block width 100% → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Caption (optional) field in *ProjectSection → Narrative Block width 100% → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.default.primary.image_caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  image_caption: prismic.KeyTextField;

  /**
   * Title field in *ProjectSection → Narrative Block width 100% → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *ProjectSection → Narrative Block width 100% → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Tag (optional) field in *ProjectSection → Narrative Block width 100% → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.default.primary.tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;
}

/**
 * Narrative Block width 100% variation for ProjectSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ProjectSection → Narrative Block  Width 80% → Primary*
 */
export interface ProjectSectionSliceNarrativeBlockWidth80Primary {
  /**
   * Image (optional) field in *ProjectSection → Narrative Block  Width 80% → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.narrativeBlockWidth80.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Caption (optional) field in *ProjectSection → Narrative Block  Width 80% → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.narrativeBlockWidth80.primary.image_caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  image_caption: prismic.KeyTextField;

  /**
   * Title field in *ProjectSection → Narrative Block  Width 80% → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.narrativeBlockWidth80.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *ProjectSection → Narrative Block  Width 80% → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.narrativeBlockWidth80.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Tag (optional) field in *ProjectSection → Narrative Block  Width 80% → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.narrativeBlockWidth80.primary.tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;
}

/**
 * Narrative Block  Width 80% variation for ProjectSection Slice
 *
 * - **API ID**: `narrativeBlockWidth80`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectSectionSliceNarrativeBlockWidth80 =
  prismic.SharedSliceVariation<
    "narrativeBlockWidth80",
    Simplify<ProjectSectionSliceNarrativeBlockWidth80Primary>,
    never
  >;

/**
 * Primary content in *ProjectSection → Image and Text width 100% → Primary*
 */
export interface ProjectSectionSliceFullWidthTextPrimary {
  /**
   * Main Image field in *ProjectSection → Image and Text width 100% → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.fullWidthText.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Description field in *ProjectSection → Image and Text width 100% → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.fullWidthText.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Image and Text width 100% variation for ProjectSection Slice
 *
 * - **API ID**: `fullWidthText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectSectionSliceFullWidthText = prismic.SharedSliceVariation<
  "fullWidthText",
  Simplify<ProjectSectionSliceFullWidthTextPrimary>,
  never
>;

/**
 * Primary content in *ProjectSection → Image and Text width 80% → Primary*
 */
export interface ProjectSectionSliceImageAndTextWidth80Primary {
  /**
   * Main Image field in *ProjectSection → Image and Text width 80% → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.imageAndTextWidth80.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Description field in *ProjectSection → Image and Text width 80% → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.imageAndTextWidth80.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Image and Text width 80% variation for ProjectSection Slice
 *
 * - **API ID**: `imageAndTextWidth80`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectSectionSliceImageAndTextWidth80 =
  prismic.SharedSliceVariation<
    "imageAndTextWidth80",
    Simplify<ProjectSectionSliceImageAndTextWidth80Primary>,
    never
  >;

/**
 * Primary content in *ProjectSection → Split Content text Right → Primary*
 */
export interface ProjectSectionSliceSplitContentPrimary {
  /**
   * Main Image field in *ProjectSection → Split Content text Right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.splitContent.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Caption (optional) field in *ProjectSection → Split Content text Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.splitContent.primary.image_caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  image_caption: prismic.KeyTextField;

  /**
   * Title field in *ProjectSection → Split Content text Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.splitContent.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *ProjectSection → Split Content text Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.splitContent.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Tag (optional) field in *ProjectSection → Split Content text Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.splitContent.primary.tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;
}

/**
 * Split Content text Right variation for ProjectSection Slice
 *
 * - **API ID**: `splitContent`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectSectionSliceSplitContent = prismic.SharedSliceVariation<
  "splitContent",
  Simplify<ProjectSectionSliceSplitContentPrimary>,
  never
>;

/**
 * Primary content in *ProjectSection → Split Content text Left → Primary*
 */
export interface ProjectSectionSliceSplitContentTextLeftPrimary {
  /**
   * Main Image field in *ProjectSection → Split Content text Left → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.splitContentTextLeft.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Caption (optional) field in *ProjectSection → Split Content text Left → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.splitContentTextLeft.primary.image_caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  image_caption: prismic.KeyTextField;

  /**
   * Title field in *ProjectSection → Split Content text Left → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.splitContentTextLeft.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *ProjectSection → Split Content text Left → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.splitContentTextLeft.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Tag (optional) field in *ProjectSection → Split Content text Left → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.splitContentTextLeft.primary.tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;
}

/**
 * Split Content text Left variation for ProjectSection Slice
 *
 * - **API ID**: `splitContentTextLeft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectSectionSliceSplitContentTextLeft =
  prismic.SharedSliceVariation<
    "splitContentTextLeft",
    Simplify<ProjectSectionSliceSplitContentTextLeftPrimary>,
    never
  >;

/**
 * Primary content in *ProjectSection → Before and After Basic → Primary*
 */
export interface ProjectSectionSliceShowcaseImagesWithCaptionPrimary {
  /**
   * Before Image (optional) field in *ProjectSection → Before and After Basic → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.showcaseImagesWithCaption.primary.image_one
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_one: prismic.ImageField<never>;

  /**
   * Before Title field in *ProjectSection → Before and After Basic → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.showcaseImagesWithCaption.primary.title_one
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_one: prismic.RichTextField;

  /**
   * Before Description field in *ProjectSection → Before and After Basic → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.showcaseImagesWithCaption.primary.description_one
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description_one: prismic.RichTextField;

  /**
   * After Image field in *ProjectSection → Before and After Basic → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.showcaseImagesWithCaption.primary.image_two
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_two: prismic.ImageField<never>;

  /**
   * After Title (optional) field in *ProjectSection → Before and After Basic → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.showcaseImagesWithCaption.primary.title_two
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_two: prismic.RichTextField;

  /**
   * After Description field in *ProjectSection → Before and After Basic → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.showcaseImagesWithCaption.primary.description_two
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description_two: prismic.RichTextField;
}

/**
 * Before and After Basic variation for ProjectSection Slice
 *
 * - **API ID**: `showcaseImagesWithCaption`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectSectionSliceShowcaseImagesWithCaption =
  prismic.SharedSliceVariation<
    "showcaseImagesWithCaption",
    Simplify<ProjectSectionSliceShowcaseImagesWithCaptionPrimary>,
    never
  >;

/**
 * Primary content in *ProjectSection → BeforeAndAfterSlider → Primary*
 */
export interface ProjectSectionSliceBeforeAndAfterSliderPrimary {
  /**
   * Before Image field in *ProjectSection → BeforeAndAfterSlider → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.beforeAndAfterSlider.primary.before_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  before_image: prismic.ImageField<never>;

  /**
   * After Image field in *ProjectSection → BeforeAndAfterSlider → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.beforeAndAfterSlider.primary.after_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  after_image: prismic.ImageField<never>;

  /**
   * Title field in *ProjectSection → BeforeAndAfterSlider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.beforeAndAfterSlider.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *ProjectSection → BeforeAndAfterSlider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.beforeAndAfterSlider.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Tag (optional) field in *ProjectSection → BeforeAndAfterSlider → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.beforeAndAfterSlider.primary.tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;
}

/**
 * BeforeAndAfterSlider variation for ProjectSection Slice
 *
 * - **API ID**: `beforeAndAfterSlider`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectSectionSliceBeforeAndAfterSlider =
  prismic.SharedSliceVariation<
    "beforeAndAfterSlider",
    Simplify<ProjectSectionSliceBeforeAndAfterSliderPrimary>,
    never
  >;

/**
 * Slice variation for *ProjectSection*
 */
type ProjectSectionSliceVariation =
  | ProjectSectionSliceDefault
  | ProjectSectionSliceNarrativeBlockWidth80
  | ProjectSectionSliceFullWidthText
  | ProjectSectionSliceImageAndTextWidth80
  | ProjectSectionSliceSplitContent
  | ProjectSectionSliceSplitContentTextLeft
  | ProjectSectionSliceShowcaseImagesWithCaption
  | ProjectSectionSliceBeforeAndAfterSlider;

/**
 * ProjectSection Shared Slice
 *
 * - **API ID**: `project_section`
 * - **Description**: ProjectSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectSectionSlice = prismic.SharedSlice<
  "project_section",
  ProjectSectionSliceVariation
>;

/**
 * Primary content in *BlogSection → Narrative Block width 100% → Primary*
 */
export interface BlogSectionSliceDefaultPrimary {
  /**
   * Image field in *BlogSection → Narrative Block width 100% → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Caption (optional) field in *BlogSection → Narrative Block width 100% → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.default.primary.image_caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  image_caption: prismic.KeyTextField;

  /**
   * Title field in *BlogSection → Narrative Block width 100% → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *BlogSection → Narrative Block width 100% → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Tag (optional) field in *BlogSection → Narrative Block width 100% → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.default.primary.tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;
}

/**
 * Narrative Block width 100% variation for BlogSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *BlogSection → Narrative Block width 80% → Primary*
 */
export interface BlogSectionSliceNarrativeBlockWidth80Primary {
  /**
   * Image field in *BlogSection → Narrative Block width 80% → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.narrativeBlockWidth80.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Caption (optional) field in *BlogSection → Narrative Block width 80% → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.narrativeBlockWidth80.primary.image_caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  image_caption: prismic.KeyTextField;

  /**
   * Title field in *BlogSection → Narrative Block width 80% → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.narrativeBlockWidth80.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *BlogSection → Narrative Block width 80% → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.narrativeBlockWidth80.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Tag (optional) field in *BlogSection → Narrative Block width 80% → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.narrativeBlockWidth80.primary.tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;
}

/**
 * Narrative Block width 80% variation for BlogSection Slice
 *
 * - **API ID**: `narrativeBlockWidth80`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogSectionSliceNarrativeBlockWidth80 =
  prismic.SharedSliceVariation<
    "narrativeBlockWidth80",
    Simplify<BlogSectionSliceNarrativeBlockWidth80Primary>,
    never
  >;

/**
 * Primary content in *BlogSection → Split Content text Right → Primary*
 */
export interface BlogSectionSliceSplitContentTextRightPrimary {
  /**
   * Image field in *BlogSection → Split Content text Right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.splitContentTextRight.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Caption (optional) field in *BlogSection → Split Content text Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.splitContentTextRight.primary.image_caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  image_caption: prismic.KeyTextField;

  /**
   * Title field in *BlogSection → Split Content text Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.splitContentTextRight.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *BlogSection → Split Content text Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.splitContentTextRight.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Tag (optional) field in *BlogSection → Split Content text Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.splitContentTextRight.primary.tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;
}

/**
 * Split Content text Right variation for BlogSection Slice
 *
 * - **API ID**: `splitContentTextRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogSectionSliceSplitContentTextRight =
  prismic.SharedSliceVariation<
    "splitContentTextRight",
    Simplify<BlogSectionSliceSplitContentTextRightPrimary>,
    never
  >;

/**
 * Slice variation for *BlogSection*
 */
type BlogSectionSliceVariation =
  | BlogSectionSliceDefault
  | BlogSectionSliceNarrativeBlockWidth80
  | BlogSectionSliceSplitContentTextRight;

/**
 * BlogSection Shared Slice
 *
 * - **API ID**: `blog_section`
 * - **Description**: BlogSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogSectionSlice = prismic.SharedSlice<
  "blog_section",
  BlogSectionSliceVariation
>;

/**
 * Item in *StorySection → Carousel of Images → Primary → Carousel Images*
 */
export interface StorySectionSliceImageCarouselPrimaryCarouselImagesItem {
  /**
   * Image field in *StorySection → Carousel of Images → Primary → Carousel Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: story_section.imageCarousel.primary.carousel_images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Caption field in *StorySection → Carousel of Images → Primary → Carousel Images*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_section.imageCarousel.primary.carousel_images[].caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caption: prismic.KeyTextField;
}

/**
 * Primary content in *StorySection → Narrative Block → Primary*
 */
export interface StorySectionSliceDefaultPrimary {
  /**
   * Image field in *StorySection → Narrative Block → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: story_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Caption (optional) field in *StorySection → Narrative Block → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_section.default.primary.image_caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  image_caption: prismic.KeyTextField;

  /**
   * Title field in *StorySection → Narrative Block → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: story_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *StorySection → Narrative Block → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Tag (optional) field in *StorySection → Narrative Block → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_section.default.primary.tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;

  /**
   * Narrative Block Width field in *StorySection → Narrative Block → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 100%
   * - **API ID Path**: story_section.default.primary.narrative_block_width
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  narrative_block_width: prismic.SelectField<"100%" | "80%", "filled">;
}

/**
 * Narrative Block variation for StorySection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StorySectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StorySectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *StorySection → Split Content → Primary*
 */
export interface StorySectionSliceSplitContentPrimary {
  /**
   * Image (optional) field in *StorySection → Split Content → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: story_section.splitContent.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Caption (optional) field in *StorySection → Split Content → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_section.splitContent.primary.image_caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  image_caption: prismic.KeyTextField;

  /**
   * Title field in *StorySection → Split Content → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_section.splitContent.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *StorySection → Split Content → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_section.splitContent.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Tag (optional) field in *StorySection → Split Content → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_section.splitContent.primary.tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;

  /**
   * Content Direction field in *StorySection → Split Content → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Text Right, Image Left
   * - **API ID Path**: story_section.splitContent.primary.content_direction
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  content_direction: prismic.SelectField<
    "Text Right, Image Left" | "Text Left, Image Right",
    "filled"
  >;

  /**
   * Split Content Width field in *StorySection → Split Content → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 100%
   * - **API ID Path**: story_section.splitContent.primary.split_content_width
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  split_content_width: prismic.SelectField<"100%" | "80%", "filled">;
}

/**
 * Split Content variation for StorySection Slice
 *
 * - **API ID**: `splitContent`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StorySectionSliceSplitContent = prismic.SharedSliceVariation<
  "splitContent",
  Simplify<StorySectionSliceSplitContentPrimary>,
  never
>;

/**
 * Primary content in *StorySection → Before And After Slider → Primary*
 */
export interface StorySectionSliceBeforeAndAfterSliderPrimary {
  /**
   * Before Image field in *StorySection → Before And After Slider → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: story_section.beforeAndAfterSlider.primary.before_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  before_image: prismic.ImageField<never>;

  /**
   * After Image field in *StorySection → Before And After Slider → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: story_section.beforeAndAfterSlider.primary.after_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  after_image: prismic.ImageField<never>;

  /**
   * Title field in *StorySection → Before And After Slider → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: story_section.beforeAndAfterSlider.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *StorySection → Before And After Slider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_section.beforeAndAfterSlider.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Tag (optional) field in *StorySection → Before And After Slider → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_section.beforeAndAfterSlider.primary.tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;

  /**
   * Before and After Slider Width field in *StorySection → Before And After Slider → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 100%
   * - **API ID Path**: story_section.beforeAndAfterSlider.primary.before_and_after_width
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  before_and_after_width: prismic.SelectField<"100%" | "80%", "filled">;
}

/**
 * Before And After Slider variation for StorySection Slice
 *
 * - **API ID**: `beforeAndAfterSlider`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StorySectionSliceBeforeAndAfterSlider =
  prismic.SharedSliceVariation<
    "beforeAndAfterSlider",
    Simplify<StorySectionSliceBeforeAndAfterSliderPrimary>,
    never
  >;

/**
 * Primary content in *StorySection → Before And After Basic → Primary*
 */
export interface StorySectionSliceBeforeAndAfterBasicPrimary {
  /**
   * Before Image field in *StorySection → Before And After Basic → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: story_section.beforeAndAfterBasic.primary.before_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  before_image: prismic.ImageField<never>;

  /**
   * Before Title field in *StorySection → Before And After Basic → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: story_section.beforeAndAfterBasic.primary.before_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  before_title: prismic.TitleField;

  /**
   * Before Description field in *StorySection → Before And After Basic → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_section.beforeAndAfterBasic.primary.before_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  before_description: prismic.RichTextField;

  /**
   * After Image field in *StorySection → Before And After Basic → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: story_section.beforeAndAfterBasic.primary.after_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  after_image: prismic.ImageField<never>;

  /**
   * After Title field in *StorySection → Before And After Basic → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: story_section.beforeAndAfterBasic.primary.after_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  after_title: prismic.TitleField;

  /**
   * After Description field in *StorySection → Before And After Basic → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_section.beforeAndAfterBasic.primary.after_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  after_description: prismic.RichTextField;

  /**
   * Before and After Basic Width field in *StorySection → Before And After Basic → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 100%
   * - **API ID Path**: story_section.beforeAndAfterBasic.primary.before_and_after_basic_width
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  before_and_after_basic_width: prismic.SelectField<
    "100%" | "80%" | "60%",
    "filled"
  >;
}

/**
 * Before And After Basic variation for StorySection Slice
 *
 * - **API ID**: `beforeAndAfterBasic`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StorySectionSliceBeforeAndAfterBasic = prismic.SharedSliceVariation<
  "beforeAndAfterBasic",
  Simplify<StorySectionSliceBeforeAndAfterBasicPrimary>,
  never
>;

/**
 * Primary content in *StorySection → Carousel of Images → Primary*
 */
export interface StorySectionSliceImageCarouselPrimary {
  /**
   * Carousel Images field in *StorySection → Carousel of Images → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: story_section.imageCarousel.primary.carousel_images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carousel_images: prismic.GroupField<
    Simplify<StorySectionSliceImageCarouselPrimaryCarouselImagesItem>
  >;
}

/**
 * Carousel of Images variation for StorySection Slice
 *
 * - **API ID**: `imageCarousel`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StorySectionSliceImageCarousel = prismic.SharedSliceVariation<
  "imageCarousel",
  Simplify<StorySectionSliceImageCarouselPrimary>,
  never
>;

/**
 * Slice variation for *StorySection*
 */
type StorySectionSliceVariation =
  | StorySectionSliceDefault
  | StorySectionSliceSplitContent
  | StorySectionSliceBeforeAndAfterSlider
  | StorySectionSliceBeforeAndAfterBasic
  | StorySectionSliceImageCarousel;

/**
 * StorySection Shared Slice
 *
 * - **API ID**: `story_section`
 * - **Description**: StorySection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StorySectionSlice = prismic.SharedSlice<
  "story_section",
  StorySectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      FeaturedProjectDocument,
      FeaturedProjectDocumentData,
      FeaturedProjectDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataLinksItem,
      OwnerDocument,
      OwnerDocumentData,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ImageSlice,
      ImageSliceDefaultPrimary,
      ImageSliceBannerPrimary,
      ImageSliceVariation,
      ImageSliceDefault,
      ImageSliceBanner,
      ImageCardsSlice,
      ImageCardsSliceDefaultPrimaryCardsItem,
      ImageCardsSliceDefaultPrimary,
      ImageCardsSliceVariation,
      ImageCardsSliceDefault,
      InspiredDesignSlice,
      InspiredDesignSliceDefaultPrimaryServicesItem,
      InspiredDesignSliceDefaultPrimary,
      InspiredDesignSliceVariation,
      InspiredDesignSliceDefault,
      QuoteSlice,
      QuoteSliceDefaultPrimary,
      QuoteSliceVariation,
      QuoteSliceDefault,
      SectionHeaderSlice,
      SectionHeaderSliceDefaultPrimary,
      SectionHeaderSliceSectionHeaderNoEyebrowPrimary,
      SectionHeaderSliceVariation,
      SectionHeaderSliceDefault,
      SectionHeaderSliceSectionHeaderNoEyebrow,
      TextSlice,
      TextSliceDefaultPrimary,
      TextSliceTwoColumnsPrimary,
      TextSliceVariation,
      TextSliceDefault,
      TextSliceTwoColumns,
      TextWithImageSlice,
      TextWithImageSliceDefaultPrimary,
      TextWithImageSliceWithButtonPrimary,
      TextWithImageSliceVariation,
      TextWithImageSliceDefault,
      TextWithImageSliceWithButton,
      FeaturedProjectsSlice,
      FeaturedProjectsSliceRatio115Primary,
      FeaturedProjectsSliceRatio151Primary,
      FeaturedProjectsSliceVariation,
      FeaturedProjectsSliceRatio115,
      FeaturedProjectsSliceRatio151,
      ProjectHeaderSlice,
      ProjectHeaderSliceDefaultPrimary,
      ProjectHeaderSliceVariation,
      ProjectHeaderSliceDefault,
      ProjectOwnerSlice,
      ProjectOwnerSliceDefaultPrimary,
      ProjectOwnerSliceVariation,
      ProjectOwnerSliceDefault,
      ProjectSectionSlice,
      ProjectSectionSliceDefaultPrimary,
      ProjectSectionSliceNarrativeBlockWidth80Primary,
      ProjectSectionSliceFullWidthTextPrimary,
      ProjectSectionSliceImageAndTextWidth80Primary,
      ProjectSectionSliceSplitContentPrimary,
      ProjectSectionSliceSplitContentTextLeftPrimary,
      ProjectSectionSliceShowcaseImagesWithCaptionPrimary,
      ProjectSectionSliceBeforeAndAfterSliderPrimary,
      ProjectSectionSliceVariation,
      ProjectSectionSliceDefault,
      ProjectSectionSliceNarrativeBlockWidth80,
      ProjectSectionSliceFullWidthText,
      ProjectSectionSliceImageAndTextWidth80,
      ProjectSectionSliceSplitContent,
      ProjectSectionSliceSplitContentTextLeft,
      ProjectSectionSliceShowcaseImagesWithCaption,
      ProjectSectionSliceBeforeAndAfterSlider,
      BlogSectionSlice,
      BlogSectionSliceDefaultPrimary,
      BlogSectionSliceNarrativeBlockWidth80Primary,
      BlogSectionSliceSplitContentTextRightPrimary,
      BlogSectionSliceVariation,
      BlogSectionSliceDefault,
      BlogSectionSliceNarrativeBlockWidth80,
      BlogSectionSliceSplitContentTextRight,
      StorySectionSlice,
      StorySectionSliceDefaultPrimary,
      StorySectionSliceSplitContentPrimary,
      StorySectionSliceBeforeAndAfterSliderPrimary,
      StorySectionSliceBeforeAndAfterBasicPrimary,
      StorySectionSliceImageCarouselPrimaryCarouselImagesItem,
      StorySectionSliceImageCarouselPrimary,
      StorySectionSliceVariation,
      StorySectionSliceDefault,
      StorySectionSliceSplitContent,
      StorySectionSliceBeforeAndAfterSlider,
      StorySectionSliceBeforeAndAfterBasic,
      StorySectionSliceImageCarousel,
    };
  }
}
