// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  featured_projects: dynamic(() => import("./FeaturedProjectsRow")),
  project_header: dynamic(() => import("./ProjectHeader")),
  project_owner: dynamic(() => import("./ProjectOwner")),
};
