// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  featured_projects: dynamic(() => import("./FeaturedProjects")),
  project_header: dynamic(() => import("./ProjectHeader")),
};
