// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  image: dynamic(() => import("./Image")),
  image_cards: dynamic(() => import("./ImageCards")),
  inspired_design: dynamic(() => import("./InspiredDesign")),
  nav_dropdown: dynamic(() => import("./NavDropdown").then((mod) => mod.NavDropdown)),
  nav_link: dynamic(() => import("./NavLink").then((mod) => mod.NavLink)),
  quote: dynamic(() => import("./Quote")),
  section_header: dynamic(() => import("./SectionHeader")),
  text: dynamic(() => import("./Text")),
  text_with_image: dynamic(() => import("./TextWithImage")),
};
