// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_header: dynamic(() => import("./BlogHeader")),
  blog_owner: dynamic(() => import("./BlogOwner")),
  blog_section: dynamic(() => import("./BlogSection")),
};
